-- MySQL Script generated by MySQL Workbench
-- Sun Jun  3 21:22:15 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema rapizz
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema rapizz
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rapizz` DEFAULT CHARACTER SET utf8mb4 ;
USE `rapizz` ;

-- -----------------------------------------------------
-- Table `rapizz`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 26
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`pizzas` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`pizzas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  `base_prix` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 15
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`assoc_pizzas_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`assoc_pizzas_ingredients` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`assoc_pizzas_ingredients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `pizza` INT(11) NOT NULL,
  `ingredient` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `ingre` (`ingredient` ASC),
  INDEX `pizz` (`pizza` ASC),
  CONSTRAINT `ingre`
    FOREIGN KEY (`ingredient`)
    REFERENCES `rapizz`.`ingredients` (`id`),
  CONSTRAINT `pizz`
    FOREIGN KEY (`pizza`)
    REFERENCES `rapizz`.`pizzas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 82
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`clients` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`clients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(20) NOT NULL,
  `adresse` VARCHAR(40) NOT NULL,
  `ville` VARCHAR(20) NOT NULL,
  `solde` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`livreur`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`livreur` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`livreur` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  `prenom` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`transports`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`transports` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`transports` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`livraisons`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`livraisons` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`livraisons` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `livreur` INT(11) NOT NULL,
  `date_livraison` DATETIME NULL DEFAULT NULL,
  `transport` INT(11) NOT NULL,
  `statut` CHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `livreur` (`livreur` ASC),
  INDEX `vehicule` (`transport` ASC),
  CONSTRAINT `livreur`
    FOREIGN KEY (`livreur`)
    REFERENCES `rapizz`.`livreur` (`id`),
  CONSTRAINT `vehicule`
    FOREIGN KEY (`transport`)
    REFERENCES `rapizz`.`transports` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`formats_pizzas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`formats_pizzas` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`formats_pizzas` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(40) NOT NULL,
  `ratio` FLOAT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `rapizz`.`commandes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `rapizz`.`commandes` ;

CREATE TABLE IF NOT EXISTS `rapizz`.`commandes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `client` INT(11) NOT NULL,
  `pizza` INT(11) NOT NULL,
  `taille` INT(2) NOT NULL,
  `tarif` FLOAT NOT NULL,
  `date_commande` DATETIME NOT NULL,
  `livraison` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `client` (`client` ASC),
  INDEX `pizza` (`pizza` ASC),
  INDEX `taille` (`taille` ASC),
  INDEX `livraison` (`livraison` ASC),
  CONSTRAINT `client`
    FOREIGN KEY (`client`)
    REFERENCES `rapizz`.`clients` (`id`),
  CONSTRAINT `livraison`
    FOREIGN KEY (`livraison`)
    REFERENCES `rapizz`.`livraisons` (`id`),
  CONSTRAINT `pizza`
    FOREIGN KEY (`pizza`)
    REFERENCES `rapizz`.`pizzas` (`id`),
  CONSTRAINT `taille`
    FOREIGN KEY (`taille`)
    REFERENCES `rapizz`.`formats_pizzas` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 21
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
